/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.attachment.validation;

/*
 * A sample validator interface for {@link org.unicase.model.attachment.FileAttachment}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator
 * plug-in to illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FileAttachmentValidator {
	boolean validate();

	boolean validateFileName(String value);

	boolean validateFileHash(String value);

	boolean validateFileID(String value);

	boolean validateFileSize(long value);
}
