/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.change.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.change.MergingProposal;
import org.unicase.model.change.ModelChangePackage;

/*
 * A sample validator interface for {@link org.unicase.model.change.MergingProposal}. This doesn't really do anything,
 * and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MergingProposalValidator {
	boolean validate();

	boolean validateConflictingProposals(EList<MergingProposal> value);

	boolean validatePendingChanges(ModelChangePackage value);
}
