/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.bug.validation;

import org.unicase.model.bug.BugStatus;
import org.unicase.model.bug.ResolutionType;
import org.unicase.model.bug.Severity;

/*
 * A sample validator interface for {@link org.unicase.model.bug.BugReport}. This doesn't really do anything, and it's
 * not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate
 * how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BugReportValidator {
	boolean validate();

	boolean validateStatus(BugStatus value);

	boolean validateSeverity(Severity value);

	boolean validateResolution(String value);

	boolean validateResolutionType(ResolutionType value);
}
