<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="urml"
    nsURI="http://unicase.org/model/urml" nsPrefix="org.unicase.model.urml">
  <eClassifiers xsi:type="ecore:EClass" name="UrmlModelElement" abstract="true" eSuperTypes="../../org.unicase.model/model/model.ecore#//UnicaseModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Stakeholder" eSuperTypes="#//UrmlModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//goal/Goal" eOpposite="#//goal/Goal/stakeholders" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URMLDiagram" eSuperTypes="../../org.unicase.model/model/model.ecore#//diagram/MEDiagram"/>
  <eSubpackages name="goal" nsURI="http://unicase.org/model/urml/goal" nsPrefix="org.unicase.model.urml.goal">
    <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//UrmlModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="soft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" upperBound="-1"
          eType="#//goal/GoalType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stakeholders" upperBound="-1"
          eType="#//Stakeholder" eOpposite="#//Stakeholder/goals" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizedFeatures" upperBound="-1"
          eType="#//feature/AbstractFeature" eOpposite="#//feature/AbstractFeature/goals"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="detailingUseCases" eType="#//usecase/ApplicationDomainUseCase"
          eOpposite="#//usecase/ApplicationDomainUseCase/detailedGoal" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subGoals" upperBound="-1"
          eType="#//goal/Goal" containment="true" eOpposite="#//goal/Goal/parentGoal"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentGoal" eType="#//goal/Goal"
          eOpposite="#//goal/Goal/subGoals" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="influencingGoals" upperBound="-1"
          eType="#//goal/GoalReference" eOpposite="#//goal/GoalReference/target" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="influencedGoals" upperBound="-1"
          eType="#//goal/GoalReference" eOpposite="#//goal/GoalReference/source" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GoalReference" eSuperTypes="#//UrmlModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//goal/Goal"
          eOpposite="#//goal/Goal/influencedGoals" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//goal/Goal"
          eOpposite="#//goal/Goal/influencingGoals" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="#//goal/GoalReferenceType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="GoalType">
      <eLiterals name="BUSINESS_GOAL" literal="Business Goal"/>
      <eLiterals name="PRODUCT_GOAL" value="1" literal="Product Goal"/>
      <eLiterals name="CUSTOMER_GOAL" value="2" literal="Customer Goal"/>
      <eLiterals name="END_USER_GOAL" value="3" literal="End User Goal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="GoalReferenceType">
      <eLiterals name="PLUS_PLUS" literal="++"/>
      <eLiterals name="PLUS" value="1" literal="+"/>
      <eLiterals name="MINUS" value="2" literal="-"/>
      <eLiterals name="MINUS_MINUS" value="3" literal="--"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="requirement" nsURI="http://unicase.org/model/urml/requirement"
      nsPrefix="org.unicase.model.urml.requirement">
    <eClassifiers xsi:type="ecore:EClass" name="Requirement" abstract="true" eSuperTypes="#//danger/Mitigation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementingServices"
          upperBound="-1" eType="#//service/Service" eOpposite="#//service/Service/satisfiedRequirements"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subRequirements" upperBound="-1"
          eType="#//requirement/Requirement" containment="true" eOpposite="#//requirement/Requirement/parentRequirement"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentRequirement" eType="#//requirement/Requirement"
          eOpposite="#//requirement/Requirement/subRequirements" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminal" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionalRequirement" eSuperTypes="#//requirement/Requirement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="detailedFeatures" upperBound="-1"
          eType="#//feature/AbstractFeature" eOpposite="#//feature/AbstractFeature/detailingFunctionalRequirements"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NonFunctionalRequirement" eSuperTypes="#//requirement/Requirement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedFeatures"
          upperBound="-1" eType="#//feature/AbstractFeature" eOpposite="#//feature/AbstractFeature/constrainingNonFunctionalRequirements"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="usecase" nsURI="http://unicase.org/model/urml/usecase" nsPrefix="org.unicase.model.urml.usecase">
    <eClassifiers xsi:type="ecore:EClass" name="UseCase" abstract="true" eSuperTypes="#//UrmlModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
          eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//requirement/Step"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
          eType="#//usecase/Actor" eOpposite="#//usecase/Actor/useCases" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ApplicationDomainUseCase" eSuperTypes="#//usecase/UseCase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="detailedGoal" upperBound="-1"
          eType="#//goal/Goal" eOpposite="#//goal/Goal/detailingUseCases" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SolutionDomainUseCase" eSuperTypes="#//usecase/UseCase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="detailedFeature" eType="#//feature/AbstractFeature"
          eOpposite="#//feature/AbstractFeature/detailingUseCases" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//danger/Asset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="useCases" upperBound="-1"
          eType="#//usecase/UseCase" eOpposite="#//usecase/UseCase/actors" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="service" nsURI="http://unicase.org/model/urml/service" nsPrefix="org.unicase.model.urml.service">
    <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//danger/Asset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="satisfiedRequirements"
          upperBound="-1" eType="#//requirement/Requirement" eOpposite="#//requirement/Requirement/implementingServices"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usedClasses" upperBound="-1"
          eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//classes/Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentService" eType="#//service/Service"
          eOpposite="#//service/Service/subServices" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subServices" upperBound="-1"
          eType="#//service/Service" containment="true" eOpposite="#//service/Service/parentService"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="danger" nsURI="http://unicase.org/model/urml/danger" nsPrefix="org.unicase.model.urml.danger">
    <eClassifiers xsi:type="ecore:EClass" name="Asset" abstract="true" eSuperTypes="#//UrmlModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="triggeredDangers" upperBound="-1"
          eType="#//danger/Danger" eOpposite="#//danger/Danger/triggeringAssets" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="harmingDangers" upperBound="-1"
          eType="#//danger/Danger" eOpposite="#//danger/Danger/harmedAssets" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Danger" eSuperTypes="#//UrmlModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="triggeringAssets" upperBound="-1"
          eType="#//danger/Asset" eOpposite="#//danger/Asset/triggeredDangers" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="harmedAssets" upperBound="-1"
          eType="#//danger/Asset" eOpposite="#//danger/Asset/harmingDangers" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="harmedClasses" upperBound="-1"
          eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//classes/Class"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mitigations" upperBound="-1"
          eType="#//danger/Mitigation" eOpposite="#//danger/Mitigation/mitigatedDangers"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Mitigation" abstract="true" eSuperTypes="#//UrmlModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mitigatedDangers" upperBound="-1"
          eType="#//danger/Danger" eOpposite="#//danger/Danger/mitigations" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProceduralMitigation" eSuperTypes="#//danger/Mitigation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mitigationProcedure"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="feature" nsURI="http://unicase.org/model/urml/feature" nsPrefix="org.unicase.model.urml.feature">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractFeature" abstract="true" eSuperTypes="#//UrmlModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
          eType="#//goal/Goal" eOpposite="#//goal/Goal/realizedFeatures" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="detailingFunctionalRequirements"
          upperBound="-1" eType="#//requirement/FunctionalRequirement" eOpposite="#//requirement/FunctionalRequirement/detailedFeatures"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constrainingNonFunctionalRequirements"
          upperBound="-1" eType="#//requirement/NonFunctionalRequirement" eOpposite="#//requirement/NonFunctionalRequirement/constrainedFeatures"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="detailingUseCases" upperBound="-1"
          eType="#//usecase/SolutionDomainUseCase" eOpposite="#//usecase/SolutionDomainUseCase/detailedFeature"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentFeature" eType="#//feature/AbstractFeature"
          eOpposite="#//feature/AbstractFeature/subFeatures" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subFeatures" upperBound="-1"
          eType="#//feature/AbstractFeature" containment="true" eOpposite="#//feature/AbstractFeature/parentFeature"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="excludingFeatures" upperBound="-1"
          eType="#//feature/AbstractFeature" eOpposite="#//feature/AbstractFeature/excludedFeatures"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="excludedFeatures" upperBound="-1"
          eType="#//feature/AbstractFeature" eOpposite="#//feature/AbstractFeature/excludingFeatures"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requieringFeatures" upperBound="-1"
          eType="#//feature/AbstractFeature" eOpposite="#//feature/AbstractFeature/requieredFeatures"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requieredFeatures" upperBound="-1"
          eType="#//feature/AbstractFeature" eOpposite="#//feature/AbstractFeature/requieringFeatures"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variationPointInstances"
          upperBound="-1" eType="#//feature/VariationPointInstance" eOpposite="#//feature/VariationPointInstance/selectedFeatures"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//feature/AbstractFeature"/>
    <eClassifiers xsi:type="ecore:EClass" name="VariationPoint" eSuperTypes="#//feature/AbstractFeature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
          eType="#//feature/VariationPointInstance" eOpposite="#//feature/VariationPointInstance/variationPoint"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rules" eType="#//feature/VariationPointRule"
          containment="true" eOpposite="#//feature/VariationPointRule/variationPoint"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariationPointInstance" eSuperTypes="#//UrmlModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variationPoint" eType="#//feature/VariationPoint"
          eOpposite="#//feature/VariationPoint/instances" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="product" eType="#//feature/Product"
          eOpposite="#//feature/Product/variationPointInstances" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="selectedFeatures" upperBound="-1"
          eType="#//feature/AbstractFeature" eOpposite="#//feature/AbstractFeature/variationPointInstances"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//UrmlModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variationPointInstances"
          upperBound="-1" eType="#//feature/VariationPointInstance" eOpposite="#//feature/VariationPointInstance/product"
          eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariationPointRule" abstract="true"
        eSuperTypes="#//UrmlModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variationPoint" eType="#//feature/VariationPoint"
          eOpposite="#//feature/VariationPoint/rules" eKeys="../../org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OneOutManyRule" eSuperTypes="#//feature/VariationPointRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="ManyOutManyRule" eSuperTypes="#//feature/VariationPointRule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
