/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.organization.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.organization.Group;
import org.unicase.model.task.WorkItem;

/*
 * A sample validator interface for {@link org.unicase.model.organization.OrgUnit}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OrgUnitValidator {
	boolean validate();

	boolean validateAcOrgId(String value);

	boolean validateGroupMemberships(EList<Group> value);

	boolean validateAssignments(EList<WorkItem> value);

	boolean validateParticipations(EList<WorkItem> value);
}
