/**
 * <copyright> Copyright (c) 2008-2009 Jonas Helming, Maximilian Koegel. All rights reserved. This program and the
 * accompanying materials are made available under the terms of the Eclipse Public License v1.0 which accompanies this
 * distribution, and is available at http://www.eclipse.org/legal/epl-v10.html </copyright>
 */
package org.unicase.workspace.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.unicase.workspace.util.WorkspaceAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers. The adapters generated by this
 * factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The adapters
 * also support Eclipse property sheets. Note that most of the adapters are shared among multiple instances. <!--
 * begin-user-doc --> <!-- end-user-doc -->
 * 
 * @generated
 */
public class WorkspaceItemProviderAdapterFactory extends WorkspaceAdapterFactory implements ComposeableAdapterFactory,
	IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public WorkspaceItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.unicase.workspace.Workspace} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected WorkspaceItemProvider workspaceItemProvider;

	/**
	 * This creates an adapter for a {@link org.unicase.workspace.Workspace}. <!-- begin-user-doc --> <!-- end-user-doc
	 * -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createWorkspaceAdapter() {
		if (workspaceItemProvider == null) {
			workspaceItemProvider = new WorkspaceItemProvider(this);
		}

		return workspaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.unicase.workspace.ServerInfo} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected ServerInfoItemProvider serverInfoItemProvider;

	/**
	 * This creates an adapter for a {@link org.unicase.workspace.ServerInfo}. <!-- begin-user-doc --> <!-- end-user-doc
	 * -->
	 * 
	 * @generated
	 */
	@Override
	public Adapter createServerInfoAdapter() {
		if (serverInfoItemProvider == null) {
			serverInfoItemProvider = new ServerInfoItemProvider(this);
		}

		return serverInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.unicase.workspace.Usersession} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected UsersessionItemProvider usersessionItemProvider;

	/**
	 * This creates an adapter for a {@link org.unicase.workspace.Usersession}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUsersessionAdapter() {
		if (usersessionItemProvider == null) {
			usersessionItemProvider = new UsersessionItemProvider(this);
		}

		return usersessionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.unicase.workspace.ProjectSpace} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected ProjectSpaceItemProvider projectSpaceItemProvider;

	/**
	 * This creates an adapter for a {@link org.unicase.workspace.ProjectSpace}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProjectSpaceAdapter() {
		if (projectSpaceItemProvider == null) {
			projectSpaceItemProvider = new ProjectSpaceItemProvider(this);
		}

		return projectSpaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.unicase.workspace.OperationComposite} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected OperationCompositeItemProvider operationCompositeItemProvider;

	/**
	 * This creates an adapter for a {@link org.unicase.workspace.OperationComposite}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationCompositeAdapter() {
		if (operationCompositeItemProvider == null) {
			operationCompositeItemProvider = new OperationCompositeItemProvider(this);
		}

		return operationCompositeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.unicase.workspace.PendingFileTransfer} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected PendingFileTransferItemProvider pendingFileTransferItemProvider;

	/**
	 * This creates an adapter for a {@link org.unicase.workspace.PendingFileTransfer}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPendingFileTransferAdapter() {
		if (pendingFileTransferItemProvider == null) {
			pendingFileTransferItemProvider = new PendingFileTransferItemProvider(this);
		}

		return pendingFileTransferItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.unicase.workspace.EventComposite} instances. <!--
	 * begin-user-doc --> <!-- end-user-doc -->
	 * 
	 * @generated
	 */
	protected EventCompositeItemProvider eventCompositeItemProvider;

	/**
	 * This creates an adapter for a {@link org.unicase.workspace.EventComposite}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEventCompositeAdapter() {
		if (eventCompositeItemProvider == null) {
			eventCompositeItemProvider = new EventCompositeItemProvider(this);
		}

		return eventCompositeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.unicase.workspace.NotificationComposite} instances.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	protected NotificationCompositeItemProvider notificationCompositeItemProvider;

	/**
	 * This creates an adapter for a {@link org.unicase.workspace.NotificationComposite}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNotificationCompositeAdapter() {
		if (notificationCompositeItemProvider == null) {
			notificationCompositeItemProvider = new NotificationCompositeItemProvider(this);
		}

		return notificationCompositeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc --> <!--
	 * end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (workspaceItemProvider != null)
			workspaceItemProvider.dispose();
		if (serverInfoItemProvider != null)
			serverInfoItemProvider.dispose();
		if (usersessionItemProvider != null)
			usersessionItemProvider.dispose();
		if (projectSpaceItemProvider != null)
			projectSpaceItemProvider.dispose();
		if (operationCompositeItemProvider != null)
			operationCompositeItemProvider.dispose();
		if (pendingFileTransferItemProvider != null)
			pendingFileTransferItemProvider.dispose();
		if (eventCompositeItemProvider != null)
			eventCompositeItemProvider.dispose();
		if (notificationCompositeItemProvider != null)
			notificationCompositeItemProvider.dispose();
	}

}
