/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tum_kinect_api_poc_JNiCallBackExample */

#ifndef _Included_de_tum_kinect_api_poc_JNiCallBackExample
#define _Included_de_tum_kinect_api_poc_JNiCallBackExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tum_kinect_api_poc_JNiCallBackExample
 * Method:    initConfig
 * Signature: (Lde/tum/kinect/api/poc/JNiCallBackExample;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tum_kinect_api_poc_JNiCallBackExample_initConfig
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
