/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.task.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.task.WorkItem;

/*
 * A sample validator interface for {@link org.unicase.model.task.WorkPackage}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkPackageValidator {
	boolean validate();

	boolean validateContainedWorkItems(EList<WorkItem> value);

	boolean validateStartDate(Date value);

	boolean validateEndDate(Date value);
}
