// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package microsoftkinectwrapper;

@net.sf.jni4net.attributes.ClrType
public class KinectHandler extends system.Object implements microsoftkinectwrapper.IKinectHandler {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected KinectHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public KinectHandler() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        microsoftkinectwrapper.KinectHandler.__ctorKinectHandler0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorKinectHandler0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String setUpAndRun();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String testSkeletonTracking();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getSkeleton();
    
    public static system.Type typeof() {
        return microsoftkinectwrapper.KinectHandler.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        microsoftkinectwrapper.KinectHandler.staticType = staticType;
    }
    //</generated-proxy>
}
