<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esmodel"
    nsURI="http://unicase.org/esmodel" nsPrefix="org.unicase.esmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Version">
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectState" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//Project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primarySpec" lowerBound="1"
        eType="#//PrimaryVersionSpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tagSpecs" upperBound="-1"
        eType="#//TagVersionSpec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextVersion" eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousVersion" eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="changes" lowerBound="1"
        eType="#//ChangePackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectHistory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" lowerBound="1"
        upperBound="-1" eType="#//Version" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionSpec" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryVersionSpec"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateVersionSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagVersionSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangePackage">
    <eOperations name="reverse" eType="#//ChangePackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fowardDelta" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore.change/model/Change.ecore#//ChangeDescription"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backwardDelta" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore.change/model/Change.ecore#//ChangeDescription"/>
  </eClassifiers>
</ecore:EPackage>
