<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testspec"
    nsURI="http://unicase.org/model/testspec" nsPrefix="org.unicase.model.testspec">
  <eClassifiers xsi:type="ecore:EClass" name="TestProtocol" eSuperTypes="platform:/plugin/org.unicase.model/model/model.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testReport" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testState" eType="#//EnumState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCase" eType="#//LogicalTestCase"
        eKeys="platform:/plugin/org.unicase.model/model/model.ecore#//IdentifiableElement/identifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumState">
    <eLiterals name="passed"/>
    <eLiterals name="failed" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalTestCase" eSuperTypes="platform:/plugin/org.unicase.model/model/model.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EnumType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postcondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infrastructure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nonFunctionalRequirement"
        eType="ecore:EClass platform:/plugin/org.unicase.model/model/model.ecore#//requirement/NonFunctionalRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalRequirement"
        eType="ecore:EClass platform:/plugin/org.unicase.model/model/model.ecore#//requirement/FunctionalRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" upperBound="-1" eType="#//TestStep"
        eKeys="platform:/plugin/org.unicase.model/model/model.ecore#//IdentifiableElement/identifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumType">
    <eLiterals name="unit"/>
    <eLiterals name="system" value="1" literal=""/>
    <eLiterals name="integration" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestStep" eSuperTypes="platform:/plugin/org.unicase.model/model/model.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exception" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputParamter" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputParameter" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
