<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://unicase.org/model" nsPrefix="org.unicase.model">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true">
    <eOperations name="getProject" eType="#//Project"/>
    <eOperations name="addReader">
      <eParameters name="readerName" eType="#//organization/User"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="https://www.sysiphus.org/Visibility">
        <details key="VisibilityValue" value="MANDATORY"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.sysiphus.org/Visibility">
        <details key="VisibilityValue" value="VIEWWHENSET"/>
      </eAnnotations>
      <eAnnotations source="http://www.unicase.org/UIHints">
        <details key="type" value="TEXT_AREA"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" lowerBound="1"
        eType="#//ModelElementId" containment="true" eKeys="#//UniqueIdentifier/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readerInfos" upperBound="-1"
        eType="#//ReaderInfo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalRequirement" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reviewed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storyPoints" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refiningRequirements" upperBound="-1"
        eType="#//FunctionalRequirement" containment="true" eOpposite="#//FunctionalRequirement/refinedRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedRequirement" eType="#//FunctionalRequirement"
        eOpposite="#//FunctionalRequirement/refiningRequirements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LeafSection" eSuperTypes="#//Section">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementClass">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
        <eTypeArguments>
          <eUpperBound eClassifier="#//ModelElement"/>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeSection" eSuperTypes="#//Section">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsections" upperBound="-1"
        eType="#//Section" containment="true" eOpposite="#//Section/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section" abstract="true" interface="true"
      eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//CompositeSection"
        eOpposite="#//CompositeSection/subsections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eOperations name="addModelElement">
      <eParameters name="modelElement" eType="#//ModelElement"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementId" eSuperTypes="#//UniqueIdentifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueIdentifier" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Default Value Literal&#x9;" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReaderInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readerId" eType="#//organization/OrgUnitId"/>
  </eClassifiers>
  <eSubpackages name="organization" nsURI="http://unicase.org/model/organisation"
      nsPrefix="org.unicase.model.organisation">
    <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//ModelElement #//organization/OrgUnit"/>
    <eClassifiers xsi:type="ecore:EClass" name="OrgUnit" eSuperTypes="#//ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="orgId" eType="#//organization/OrgUnitId"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrgUnitId" eSuperTypes="#//UniqueIdentifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//organization/OrgUnit"/>
  </eSubpackages>
  <eSubpackages name="diagram" nsURI="http://unicase.org/model/diagram" nsPrefix="org.unicase.model.diagram">
    <eClassifiers xsi:type="ecore:EClass" name="MEDiagram" eSuperTypes="#//ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//ModelElement"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
