<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esmodel"
    nsURI="http://unicase.org/emfstore/esmodel" nsPrefix="org.unicase.emfstore.esmodel">
  <eClassifiers xsi:type="ecore:EClass" name="ProjectHistory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectId" eType="#//ProjectId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" lowerBound="1"
        upperBound="-1" eType="#//changemanagment/Version" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectDescription" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectId" lowerBound="1"
        eType="#//ProjectId" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" lowerBound="1"
        eType="#//changemanagment/PrimaryVersionSpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SessionId" eSuperTypes="../../org.unicase.model/model/model.ecore#//UniqueIdentifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServerSpace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orgUnits" upperBound="-1"
        eType="#//accesscontrol/ACOrgUnit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//ProjectHistory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="openSessions" upperBound="-1"
        eType="#//SessionId" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectId" eSuperTypes="../../org.unicase.model/model/model.ecore#//UniqueIdentifier"/>
  <eSubpackages name="changemanagment" nsURI="http://unicase.org/esmodel/changemanagment"
      nsPrefix="org.unicase.emfstore.esmodel.changemanagment">
    <eClassifiers xsi:type="ecore:EClass" name="TagVersionSpec" eSuperTypes="#//changemanagment/VersionSpec">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DateVersionSpec" eSuperTypes="#//changemanagment/VersionSpec">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimaryVersionSpec" eSuperTypes="#//changemanagment/VersionSpec">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VersionSpec" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="LogMessage">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChangePackage">
      <eOperations name="reverse" eType="#//changemanagment/ChangePackage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fowardDelta" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore.change/model/Change.ecore#//ChangeDescription"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="backwardDelta" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore.change/model/Change.ecore#//ChangeDescription"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HistoryInfo">
      <eStructuralFeatures xsi:type="ecore:EReference" name="primerySpec" lowerBound="1"
          eType="#//changemanagment/PrimaryVersionSpec"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="logMessage" lowerBound="1"
          eType="#//changemanagment/LogMessage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Version">
      <eStructuralFeatures xsi:type="ecore:EReference" name="projectState" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//Project"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="primarySpec" lowerBound="1"
          eType="#//changemanagment/PrimaryVersionSpec" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tagSpecs" upperBound="-1"
          eType="#//changemanagment/TagVersionSpec" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nextVersion" eType="#//changemanagment/Version"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="previousVersion" eType="#//changemanagment/Version"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="changes" eType="#//changemanagment/ChangePackage"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="logMessage" eType="#//changemanagment/LogMessage"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HeadVersionSpec" eSuperTypes="#//changemanagment/VersionSpec"/>
  </eSubpackages>
  <eSubpackages name="accesscontrol" nsURI="http://unicase.org/esmodel/accesscontrol"
      nsPrefix="org.unicase.accesscontrol">
    <eClassifiers xsi:type="ecore:EClass" name="ACUser">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ACOrgUnit">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
          eType="#//accesscontrol/roles/Role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//accesscontrol/ACOrgUnitId"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ACGroup" eSuperTypes="#//accesscontrol/ACOrgUnit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
          eType="#//accesscontrol/ACOrgUnit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ACOrgUnitId" eSuperTypes="../../org.unicase.model/model/model.ecore#//UniqueIdentifier"/>
    <eSubpackages name="roles" nsURI="http://unicase.org/esmodel/accesscontrol/roles"
        nsPrefix="org.unicase.accesscontrol.roles">
      <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true">
        <eOperations name="canAdministrate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="projectId" eType="#//ProjectId"/>
        </eOperations>
        <eOperations name="canCreate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="projectId" eType="#//ProjectId"/>
          <eParameters name="modelElement" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//ModelElement"/>
        </eOperations>
        <eOperations name="canDelete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="projectId" eType="#//ProjectId"/>
          <eParameters name="modelElement" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//ModelElement"/>
        </eOperations>
        <eOperations name="canModify" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="projectId" eType="#//ProjectId"/>
          <eParameters name="modelElement" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//ModelElement"/>
        </eOperations>
        <eOperations name="canRead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="projectId" eType="#//ProjectId"/>
          <eParameters name="modelElement" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//ModelElement"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
            eType="#//ProjectInfo"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReaderRole" eSuperTypes="#//accesscontrol/roles/Role"/>
      <eClassifiers xsi:type="ecore:EClass" name="WriterRole" eSuperTypes="#//accesscontrol/roles/Role"/>
      <eClassifiers xsi:type="ecore:EClass" name="ProjectAdminRole" eSuperTypes="#//accesscontrol/roles/Role"/>
      <eClassifiers xsi:type="ecore:EClass" name="ServerAdmin" eSuperTypes="#//accesscontrol/roles/Role"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
