<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esmodel"
    nsURI="http://unicase.org/emfstore/esmodel" nsPrefix="org.unicase.emfstore.esmodel">
  <eClassifiers xsi:type="ecore:EClass" name="ProjectHistory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectId" eType="#//ProjectId"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" lowerBound="1"
        upperBound="-1" eType="#//versioning/Version"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectDescription" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectId" lowerBound="1"
        eType="#//ProjectId" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" lowerBound="1"
        eType="#//versioning/PrimaryVersionSpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SessionId" eSuperTypes="../../org.unicase.model/model/model.ecore#//UniqueIdentifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServerSpace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//accesscontrol/ACGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//ProjectHistory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="openSessions" upperBound="-1"
        eType="#//SessionId" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//accesscontrol/ACUser" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectId" eSuperTypes="../../org.unicase.model/model/model.ecore#//UniqueIdentifier"/>
  <eSubpackages name="versioning" nsURI="http://unicase.org/esmodel/versioning" nsPrefix="org.unicase.emfstore.esmodel.versioning">
    <eClassifiers xsi:type="ecore:EClass" name="TagVersionSpec" eSuperTypes="#//versioning/VersionSpec">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DateVersionSpec" eSuperTypes="#//versioning/VersionSpec">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimaryVersionSpec" eSuperTypes="#//versioning/VersionSpec">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VersionSpec" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="LogMessage">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChangePackage">
      <eOperations name="reverse" eType="#//versioning/ChangePackage"/>
      <eOperations name="apply">
        <eParameters name="project" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//Project"/>
      </eOperations>
      <eOperations name="init">
        <eParameters name="project" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//Project"/>
        <eParameters name="backwardChangeDescription" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore.change/model/Change.ecore#//ChangeDescription"/>
      </eOperations>
      <eOperations name="getOperations" upperBound="-1" eType="#//versioning/operations/AbstractOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="changeContainers" upperBound="-1"
          eType="#//versioning/changeContainer/ChangeContainer" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HistoryInfo">
      <eStructuralFeatures xsi:type="ecore:EReference" name="primerySpec" lowerBound="1"
          eType="#//versioning/PrimaryVersionSpec"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="logMessage" lowerBound="1"
          eType="#//versioning/LogMessage"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Version">
      <eStructuralFeatures xsi:type="ecore:EReference" name="projectState" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//Project"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="primarySpec" lowerBound="1"
          eType="#//versioning/PrimaryVersionSpec" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tagSpecs" upperBound="-1"
          eType="#//versioning/TagVersionSpec" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nextVersion" eType="#//versioning/Version"
          eOpposite="#//versioning/Version/previousVersion"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="previousVersion" eType="#//versioning/Version"
          eOpposite="#//versioning/Version/nextVersion"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="changes" eType="#//versioning/ChangePackage"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="logMessage" eType="#//versioning/LogMessage"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HeadVersionSpec" eSuperTypes="#//versioning/VersionSpec"/>
    <eSubpackages name="operations" nsURI="http://unicase.org/esmodel/versioning/operations"
        nsPrefix="org.unicase.emfstore.esmodel.versioning.operations">
      <eClassifiers xsi:type="ecore:EClass" name="AbstractOperation">
        <eOperations name="apply">
          <eParameters name="project" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//Project"/>
        </eOperations>
        <eOperations name="reverse" eType="#//versioning/operations/AbstractOperation"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="modelElement" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//ModelElement"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CompositeOperation" eSuperTypes="#//versioning/operations/AbstractOperation">
        <eStructuralFeatures xsi:type="ecore:EReference" name="atomicOperations" upperBound="-1"
            eType="#//versioning/operations/AtomicOperation"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FeatureOperation" eSuperTypes="#//versioning/operations/AtomicOperation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="AttributeName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CreateOperation" eSuperTypes="#//versioning/operations/AtomicOperation">
        <eStructuralFeatures xsi:type="ecore:EReference" name="objectToCreate" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DeleteOperation" eSuperTypes="#//versioning/operations/AtomicOperation">
        <eStructuralFeatures xsi:type="ecore:EReference" name="objectToDelete" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AtomicOperation" eSuperTypes="#//versioning/operations/AbstractOperation"/>
    </eSubpackages>
    <eSubpackages name="changeContainer" nsURI="http://unicase.org/esmodel/versioning/changeContainer"
        nsPrefix="org.unicase.emfstore.esmodel.versioning.changeContainer">
      <eClassifiers xsi:type="ecore:EClass" name="ChangeContainer">
        <eOperations name="reverse" eType="#//versioning/changeContainer/ChangeContainer"/>
        <eOperations name="apply">
          <eParameters name="project" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//Project"/>
        </eOperations>
        <eOperations name="getOperations" upperBound="-1" eType="#//versioning/operations/AbstractOperation"/>
        <eOperations name="init">
          <eParameters name="project" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//Project"/>
          <eParameters name="backwardChangeDescription" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore.change/model/Change.ecore#//ChangeDescription"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="forwardDelta" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="teneo.jpa">
            <details key="value" value="@Type(type=&quot;text&quot;)"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="backwardDelta" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="teneo.jpa">
            <details key="value" value="@Type(type=&quot;text&quot;)"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CompositeChangeContainer" eSuperTypes="#//versioning/changeContainer/ChangeContainer">
        <eOperations name="init">
          <eParameters name="project" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//Project"/>
          <eParameters name="backwardChangeDescription" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore.change/model/Change.ecore#//ChangeDescription"/>
          <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eParameters name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="accesscontrol" nsURI="http://unicase.org/esmodel/accesscontrol"
      nsPrefix="org.unicase.accesscontrol">
    <eClassifiers xsi:type="ecore:EClass" name="ACUser" eSuperTypes="#//accesscontrol/ACOrgUnit">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ACOrgUnit" eSuperTypes="../../org.unicase.model/model/model.ecore#//IdentifiableElement">
      <eOperations name="getId" eType="#//accesscontrol/ACOrgUnitId"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
          eType="#//accesscontrol/roles/Role" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ACGroup" eSuperTypes="#//accesscontrol/ACOrgUnit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
          eType="#//accesscontrol/ACOrgUnit" eKeys="../../org.unicase.model/model/model.ecore#//IdentifiableElement/identifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ACOrgUnitId" eSuperTypes="../../org.unicase.model/model/model.ecore#//UniqueIdentifier"/>
    <eSubpackages name="roles" nsURI="http://unicase.org/esmodel/accesscontrol/roles"
        nsPrefix="org.unicase.accesscontrol.roles">
      <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true">
        <eOperations name="canAdministrate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="projectId" eType="#//ProjectId"/>
        </eOperations>
        <eOperations name="canCreate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="projectId" eType="#//ProjectId"/>
          <eParameters name="modelElement" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//ModelElement"/>
        </eOperations>
        <eOperations name="canDelete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="projectId" eType="#//ProjectId"/>
          <eParameters name="modelElement" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//ModelElement"/>
        </eOperations>
        <eOperations name="canModify" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="projectId" eType="#//ProjectId"/>
          <eParameters name="modelElement" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//ModelElement"/>
        </eOperations>
        <eOperations name="canRead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="projectId" eType="#//ProjectId"/>
          <eParameters name="modelElement" eType="ecore:EClass ../../org.unicase.model/model/model.ecore#//ModelElement"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
            eType="#//ProjectId" eKeys="../../org.unicase.model/model/model.ecore#//UniqueIdentifier/id"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReaderRole" eSuperTypes="#//accesscontrol/roles/Role"/>
      <eClassifiers xsi:type="ecore:EClass" name="WriterRole" eSuperTypes="#//accesscontrol/roles/Role"/>
      <eClassifiers xsi:type="ecore:EClass" name="ProjectAdminRole" eSuperTypes="#//accesscontrol/roles/Role"/>
      <eClassifiers xsi:type="ecore:EClass" name="ServerAdmin" eSuperTypes="#//accesscontrol/roles/Role"/>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
