/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.activity.validation;

import org.unicase.model.activity.ActivityObject;

/*
 * A sample validator interface for {@link org.unicase.model.activity.Transition}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransitionValidator {
	boolean validate();

	boolean validateSource(ActivityObject value);

	boolean validateTarget(ActivityObject value);

	boolean validateCondition(String value);
}
