<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://unicase.org/testspecmodel" nsPrefix="org.unicase.testspec.model">
  <eClassifiers xsi:type="ecore:EClass" name="TestProtocol" eSuperTypes="platform:/plugin/org.unicase.model/model/model.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testReport" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testState" eType="#//EnumState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCase" eType="#//TestCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumState">
    <eLiterals name="passed"/>
    <eLiterals name="failed" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase" eSuperTypes="platform:/plugin/org.unicase.model/model/model.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precondition" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postcondition" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infrastructure" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nonFunctionalRequirement"
        eType="ecore:EClass platform:/plugin/org.unicase.model/model/model.ecore#//requirement/NonFunctionalRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalRequirement"
        eType="ecore:EClass platform:/plugin/org.unicase.model/model/model.ecore#//requirement/FunctionalRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" upperBound="-1" eType="#//TestStep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumType">
    <eLiterals name="unit"/>
    <eLiterals name="system" value="1"/>
    <eLiterals name="integration" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestStep" eSuperTypes="platform:/plugin/org.unicase.model/model/model.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exception" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
</ecore:EPackage>
