/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.document.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.ModelElement;

/*
 * A sample validator interface for {@link org.unicase.model.document.LeafSection}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LeafSectionValidator {
	boolean validate();

	boolean validateModelElements(EList<ModelElement> value);

	boolean validateReferencedModelElements(EList<ModelElement> value);
}
