/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.classes.validation;

import org.unicase.model.classes.AssociationType;

/*
 * A sample validator interface for {@link org.unicase.model.classes.Association}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssociationValidator {
	boolean validate();

	boolean validateSource(org.unicase.model.classes.Class value);

	boolean validateTarget(org.unicase.model.classes.Class value);

	boolean validateType(AssociationType value);

	boolean validateSourceMultiplicity(String value);

	boolean validateTargetMultiplicity(String value);

	boolean validateSourceRole(String value);

	boolean validateTargetRole(String value);
}
