/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.classes.validation;

import org.unicase.model.classes.ScopeType;
import org.unicase.model.classes.VisibilityType;

/*
 * A sample validator interface for {@link org.unicase.model.classes.Attribute}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValidator {
	boolean validate();

	boolean validateDefiningClass(org.unicase.model.classes.Class value);

	boolean validateVisibility(VisibilityType value);

	boolean validateScope(ScopeType value);

	boolean validateSignature(String value);

	boolean validateType(String value);

	boolean validateDefaultValue(String value);

	boolean validateProperties(String value);

	boolean validateLabel(String value);
}
