/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.classes.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.classes.Association;
import org.unicase.model.classes.Attribute;
import org.unicase.model.classes.Method;
import org.unicase.model.requirement.Scenario;
import org.unicase.model.requirement.UseCase;

/*
 * A sample validator interface for {@link org.unicase.model.classes.Class}. This doesn't really do anything, and it's
 * not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate
 * how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateParticipatedUseCases(EList<UseCase> value);

	boolean validateSuperClasses(EList<org.unicase.model.classes.Class> value);

	boolean validateSubClasses(EList<org.unicase.model.classes.Class> value);

	boolean validateIncomingAssociations(EList<Association> value);

	boolean validateOutgoingAssociations(EList<Association> value);

	boolean validateAttributes(EList<Attribute> value);

	boolean validateMethods(EList<Method> value);

	boolean validateDemoParticipations(EList<Scenario> value);
}
