/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.classes.validation;

import org.unicase.model.classes.PackageElement;

/*
 * A sample validator interface for {@link org.unicase.model.classes.Dependency}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DependencyValidator {
	boolean validate();

	boolean validateSource(PackageElement value);

	boolean validateTarget(PackageElement value);
}
