/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.classes.validation;

import org.unicase.model.classes.ArgumentDirectionType;

/*
 * A sample validator interface for {@link org.unicase.model.classes.MethodArgument}. This doesn't really do anything,
 * and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MethodArgumentValidator {
	boolean validate();

	boolean validateType(String value);

	boolean validateDirection(ArgumentDirectionType value);

	boolean validateDefaultValue(String value);

	boolean validateSignature(String value);

	boolean validateLabel(String value);
}
