/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.classes.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.classes.Dependency;

/*
 * A sample validator interface for {@link org.unicase.model.classes.PackageElement}. This doesn't really do anything,
 * and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageElementValidator {
	boolean validate();

	boolean validateParentPackage(org.unicase.model.classes.Package value);

	boolean validateOutgoingDependencies(EList<Dependency> value);

	boolean validateIncomingDependencies(EList<Dependency> value);
}
