<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="documentTemplate"
    nsURI="http://unicase.org/documentExport/documentTemplate" nsPrefix="org.unicase.documentExport.documentTemplate">
  <eClassifiers xsi:type="ecore:EClass" name="Template">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElementRendererMapping"
        upperBound="-1" eType="#//renderers/ModelElementRendererMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutOptions" eType="#//renderers/options/LayoutOptions"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalRendererOptions"
        upperBound="-1" eType="#//renderers/options/AttributeOption" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="renderers" nsURI="http://unicase.org/documentExport/documentTemplate/renderers"
      nsPrefix="org.unicase.documentExport.documentTemplate.renderers">
    <eClassifiers xsi:type="ecore:EClass" name="ModelElementRenderer" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rendererOptions" upperBound="-1"
          eType="#//renderers/options/RendererOption" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="#//Template"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeRenderer" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeOption" eType="#//renderers/options/AttributeOption"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DocumentRenderer" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ModelElementRendererMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="renderer" eType="#//renderers/ModelElementRenderer"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="eClassName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeRendererMapping">
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeRenderer" eType="#//renderers/AttributeRenderer"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eSubpackages name="defaultRenderers" nsURI="http://unicase.org/documentExport/documentTemplate/renderers/defaultRenderers"
        nsPrefix="org.unicase.documentExport.documentTemplate.renderers.defaultRenderers">
      <eClassifiers xsi:type="ecore:EClass" name="DefaultModelElementRenderer" eSuperTypes="#//renderers/ModelElementRenderer">
        <eStructuralFeatures xsi:type="ecore:EReference" name="attributeRendererMapping"
            upperBound="-1" eType="#//renderers/AttributeRendererMapping" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DefaultAttributeRenderer" eSuperTypes="#//renderers/AttributeRenderer"/>
      <eClassifiers xsi:type="ecore:EClass" name="DefaultDocumentRenderer" eSuperTypes="#//renderers/DocumentRenderer"/>
    </eSubpackages>
    <eSubpackages name="specialRenderers" nsURI="http://unicase.org/documentExport/documentTemplate/renderers/specialRenderers"
        nsPrefix="org.unicase.documentExport.documentTemplate.renderers.specialRenderers">
      <eClassifiers xsi:type="ecore:EClass" name="MeetingRenderer" eSuperTypes="#//renderers/ModelElementRenderer"/>
      <eClassifiers xsi:type="ecore:EClass" name="MilestoneRenderer" eSuperTypes="#//renderers/ModelElementRenderer"/>
    </eSubpackages>
    <eSubpackages name="options" nsURI="http://unicase.org/documentExport/documentTemplate/renderers/options"
        nsPrefix="org.unicase.documentExport.documentTemplate.renderers.options">
      <eClassifiers xsi:type="ecore:EClass" name="RendererOption" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeOption" abstract="true"
          eSuperTypes="#//renderers/options/RendererOption">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="hide" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
            defaultValueLiteral="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="overwriteGlobalOption"
            eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
            defaultValueLiteral="false"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SingleReferenceAttributeOption"
          eSuperTypes="#//renderers/options/ReferenceAttributeOption">
        <eStructuralFeatures xsi:type="ecore:EReference" name="globalOption" eType="#//renderers/options/SingleReferenceAttributeOption"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="referenceOption" eType="#//renderers/options/ReferenceOption"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MultiReferenceAttributeOption" eSuperTypes="#//renderers/options/ReferenceAttributeOption">
        <eStructuralFeatures xsi:type="ecore:EReference" name="globalOption" eType="#//renderers/options/MultiReferenceAttributeOption"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="referenceOption" eType="#//renderers/options/ReferenceOption"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="listOption" eType="#//renderers/options/ListOption"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReferenceOption" eSuperTypes="#//renderers/options/RendererOption">
        <eStructuralFeatures xsi:type="ecore:EReference" name="textOption" eType="#//renderers/options/TextOption"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StringAttributeOption" eSuperTypes="#//renderers/options/AttributeOption">
        <eStructuralFeatures xsi:type="ecore:EReference" name="globalOption" eType="#//renderers/options/StringAttributeOption"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="textOption" eType="#//renderers/options/TextOption"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LayoutOptions" eSuperTypes="#//renderers/options/RendererOption">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="coverText" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="coverTextTextOption"
            eType="#//renderers/options/TextOption" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="defaultTextOption"
            eType="#//renderers/options/TextOption" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sectionTextOption"
            eType="#//renderers/options/TextOption" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="hideAnnotations" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="hideAttachments" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="hideIncomingDocumentReferences"
            eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageNumberingStyle"
            eType="#//renderers/options/PageNumberingStyle"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ListOption" eSuperTypes="#//renderers/options/RendererOption">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="listStyle" eType="#//renderers/options/ListStyle"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TextOption" eSuperTypes="#//renderers/options/RendererOption">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontFamily" eType="#//renderers/options/FontFamily"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontSize" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
            defaultValueLiteral="12"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="underline" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="fontColor" eType="#//renderers/options/UColor"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReferenceAttributeOption" abstract="true"
          eSuperTypes="#//renderers/options/AttributeOption">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="contained" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="FontFamily">
        <eLiterals name="ARIAL" literal="Arial"/>
        <eLiterals name="VERDANA" value="1" literal="Verdana"/>
        <eLiterals name="TIMES_NEW_ROMAN" value="2" literal="Times new Roman"/>
        <eLiterals name="HELVETICA" value="3" literal="Helvetica"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ListStyle">
        <eLiterals name="BULLETED" literal="bulleted"/>
        <eLiterals name="JUST_NEW_LINES" value="1" literal="just new lines"/>
        <eLiterals name="SEPERATED_LIST" value="2" literal="seperated list"/>
        <eLiterals name="NUMBERED" value="3" literal="numbered"/>
        <eLiterals name="ALPHA" value="4" literal="alpha"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UColor" eSuperTypes="#//renderers/options/RendererOption">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="red" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="green" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="blue" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="PageNumberingStyle">
        <eLiterals name="PAGE_ONLY" literal="&lt;page>"/>
        <eLiterals name="PAGE_OF_PAGE_COUNT" value="1" literal="&lt;page>/&lt;page_count>"/>
        <eLiterals name="EMPTY" value="2" literal="-"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
