/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.util.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.ModelElementId;

/*
 * A sample validator interface for {@link org.unicase.model.util.ModelElementPath}. This doesn't really do anything,
 * and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelElementPathValidator {
	boolean validate();

	boolean validateSource(ModelElementId value);

	boolean validateTarget(ModelElementId value);

	boolean validatePath(EList<ModelElementId> value);
}
