// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package microsoftkinectwrapper;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class IKinectHandler_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return microsoftkinectwrapper.IKinectHandler_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        microsoftkinectwrapper.IKinectHandler_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __IKinectHandler extends system.Object implements microsoftkinectwrapper.IKinectHandler {
    
    protected __IKinectHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String setUpAndRun();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String testSkeletonTracking();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getSkeleton();
}
//</generated-proxy>
