// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package microsoftkinectwrapper;

@net.sf.jni4net.attributes.ClrInterface
public interface IKinectHandler {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    java.lang.String setUpAndRun();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    java.lang.String testSkeletonTracking();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    java.lang.String getSkeleton();
    //</generated-interface>
}
