<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="emailbundle"
    nsURI="http://unicase.org/model/emailbundle" nsPrefix="org.unicase.model.emailbundle">
  <eClassifiers xsi:type="ecore:EClass" name="Bundle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BundleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SendOption" eType="#//SendSettings"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Days" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DaysCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Weekday" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WeekdayOption" eType="#//Weekdays"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Providers" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SendSettings">
    <eLiterals name="NONE" literal="&lt;please select>"/>
    <eLiterals name="IMMEDIATELY" value="1" literal="immediately"/>
    <eLiterals name="AGGREGATED" value="2" literal="aggregated"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Weekdays">
    <eLiterals name="NONE" literal="&lt;please select>"/>
    <eLiterals name="MONDAY" value="1" literal="Monday"/>
    <eLiterals name="TUESDAY" value="2" literal="Tuesday"/>
    <eLiterals name="WEDNESDAY" value="3" literal="Wednesday"/>
    <eLiterals name="THURSDAY" value="4" literal="Thursday"/>
    <eLiterals name="FRIDAY" value="5" literal="Friday"/>
    <eLiterals name="SATURDAY" value="6" literal="Saturday"/>
    <eLiterals name="SUNDAY" value="7" literal="Sunday"/>
  </eClassifiers>
</ecore:EPackage>
