/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.requirement.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.requirement.ActorInstance;
import org.unicase.model.requirement.UseCase;
import org.unicase.model.requirement.UserTask;

/*
 * A sample validator interface for {@link org.unicase.model.requirement.Actor}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActorValidator {
	boolean validate();

	boolean validateInitiatedUserTask(UserTask value);

	boolean validateParticipatedUserTasks(EList<UserTask> value);

	boolean validateInitiatedUseCases(EList<UseCase> value);

	boolean validateParticipatedUseCases(EList<UseCase> value);

	boolean validateInstances(EList<ActorInstance> value);
}
