/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.requirement.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.requirement.Actor;
import org.unicase.model.requirement.Scenario;

/*
 * A sample validator interface for {@link org.unicase.model.requirement.ActorInstance}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator
 * plug-in to illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActorInstanceValidator {
	boolean validate();

	boolean validateInitiatedScenarios(EList<Scenario> value);

	boolean validateParticipatedScenarios(EList<Scenario> value);

	boolean validateInstantiatedActor(Actor value);
}
