/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.requirement.validation;

import org.unicase.model.requirement.SystemFunction;
import org.unicase.model.requirement.UseCase;

/*
 * A sample validator interface for {@link org.unicase.model.requirement.Step}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StepValidator {
	boolean validate();

	boolean validateUserStep(boolean value);

	boolean validateIncludedUseCase(UseCase value);

	boolean validateIncludedSystemFunction(SystemFunction value);

	boolean validateUseCase(UseCase value);
}
