/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.requirement.validation;

/*
 * A sample validator interface for {@link org.unicase.model.requirement.SystemFunction}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator
 * plug-in to illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SystemFunctionValidator {
	boolean validate();

	boolean validateInput(String value);

	boolean validateOutput(String value);

	boolean validateException(String value);
}
