/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.component.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.component.ComponentService;

/*
 * A sample validator interface for {@link org.unicase.model.component.Component}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentValidator {
	boolean validate();

	boolean validatePackages(EList<org.unicase.model.classes.Package> value);

	boolean validateOfferedServices(EList<ComponentService> value);

	boolean validateConsumedServices(EList<ComponentService> value);

	boolean validateSubsystems(EList<org.unicase.model.classes.Package> value);
}
