/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.meeting.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.meeting.IssueMeetingSection;
import org.unicase.model.meeting.MeetingSection;
import org.unicase.model.meeting.WorkItemMeetingSection;
import org.unicase.model.organization.OrgUnit;
import org.unicase.model.organization.User;

/*
 * A sample validator interface for {@link org.unicase.model.meeting.Meeting}. This doesn't really do anything, and it's
 * not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate
 * how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MeetingValidator {
	boolean validate();

	boolean validateLocation(String value);

	boolean validateStarttime(Date value);

	boolean validateEndtime(Date value);

	boolean validateFacilitator(User value);

	boolean validateMinutetaker(User value);

	boolean validateTimekeeper(User value);

	boolean validateParticipants(EList<OrgUnit> value);

	boolean validateSections(EList<MeetingSection> value);

	boolean validateIdentifiedIssuesSection(IssueMeetingSection value);

	boolean validateIdentifiedWorkItemsSection(WorkItemMeetingSection value);
}
