/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.Annotation;
import org.unicase.model.Attachment;
import org.unicase.model.document.LeafSection;
import org.unicase.model.profile.StereotypeInstance;
import org.unicase.model.rationale.Comment;

/*
 * A sample validator interface for {@link org.unicase.model.ModelElement}. This doesn't really do anything, and it's
 * not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate
 * how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelElementValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateDescription(String value);

	boolean validateCreator(String value);

	boolean validateCreationDate(Date value);

	boolean validateAnnotations(EList<Annotation> value);

	boolean validateAttachments(EList<Attachment> value);

	boolean validateIncomingDocumentReferences(EList<LeafSection> value);

	boolean validateLeafSection(LeafSection value);

	boolean validateState(String value);

	boolean validateAppliedStereotypeInstances(EList<StereotypeInstance> value);

	boolean validateComments(EList<Comment> value);
}
