/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.ModelElement;

/*
 * A sample validator interface for {@link org.unicase.model.Project}. This doesn't really do anything, and it's not a
 * real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how
 * EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProjectValidator {
	boolean validate();

	boolean validateModelElements(EList<ModelElement> value);
}
