/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.profile.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.profile.Profile;
import org.unicase.model.profile.StereotypeAttribute;
import org.unicase.model.profile.StereotypeInstance;

/*
 * A sample validator interface for {@link org.unicase.model.profile.Stereotype}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StereotypeValidator {
	boolean validate();

	boolean validateRequired(boolean value);

	boolean validateProfile(Profile value);

	boolean validateStereotypeInstances(EList<StereotypeInstance> value);

	boolean validateStereotypeAttributes(EList<StereotypeAttribute> value);
}
