/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.profile.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.profile.Stereotype;
import org.unicase.model.profile.StereotypeAttributeInstance;

/*
 * A sample validator interface for {@link org.unicase.model.profile.StereotypeAttribute}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator
 * plug-in to illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StereotypeAttributeValidator {
	boolean validate();

	boolean validateStereotype(Stereotype value);

	boolean validateStereotypeAttributeInstances(EList<StereotypeAttributeInstance> value);
}
