/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.profile.validation;

import org.unicase.model.profile.StereotypeAttribute;
import org.unicase.model.profile.StereotypeInstance;

/*
 * A sample validator interface for {@link org.unicase.model.profile.StereotypeAttributeInstance}. This doesn't really
 * do anything, and it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator
 * plug-in to illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StereotypeAttributeInstanceValidator {
	boolean validate();

	boolean validateStereotypeInstance(StereotypeInstance value);

	boolean validateStereotypeAttribute(StereotypeAttribute value);
}
