/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.state.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.state.Transition;

/*
 * A sample validator interface for {@link org.unicase.model.state.State}. This doesn't really do anything, and it's not
 * a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how
 * EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateValidator {
	boolean validate();

	boolean validateExitConditions(String value);

	boolean validateActivities(String value);

	boolean validateEntryConditions(String value);

	boolean validateOutgoingTransitions(EList<Transition> value);

	boolean validateIncomingTransitions(EList<Transition> value);
}
