<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testspec"
    nsURI="http://unicase.org/model/testspec" nsPrefix="org.unicase.model.testspec">
  <eClassifiers xsi:type="ecore:EClass" name="TestProtocol" eSuperTypes="platform:/plugin/org.unicase.model/model/model.ecore#//UnicaseModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testReport" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="10.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testState" eType="#//EnumState">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="20.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCase" eType="#//TestCase"
        eKeys="platform:/plugin/org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="30.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testSteps" eType="#//TestStep"
        eKeys="platform:/plugin/org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="1.0"/>
        <details key="position" value="bottom"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumState">
    <eLiterals name="unset" value="2" literal="unset"/>
    <eLiterals name="passed"/>
    <eLiterals name="failed" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCase" eSuperTypes="platform:/plugin/org.unicase.model/model/model.ecore#//UnicaseModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EnumType">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="10.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="20.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postcondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="30.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infrastructure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="40.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nonFunctionalRequirement"
        eType="ecore:EClass platform:/plugin/org.unicase.model/model/model.ecore#//requirement/NonFunctionalRequirement">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="60.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalRequirement"
        eType="ecore:EClass platform:/plugin/org.unicase.model/model/model.ecore#//requirement/FunctionalRequirement">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="50.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" upperBound="-1" eType="#//TestStep"
        eKeys="platform:/plugin/org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="70.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumType">
    <eLiterals name="unit"/>
    <eLiterals name="system" value="1" literal="system"/>
    <eLiterals name="integration" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestStep" eSuperTypes="platform:/plugin/org.unicase.model/model/model.ecore#//UnicaseModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exception" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="10.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//TestStepInput" containment="true" eOpposite="#//TestStepInput/testStep"
        eKeys="platform:/plugin/org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="20.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//TestStepOutput" containment="true" eOpposite="#//TestStepOutput/testStep"
        eKeys="platform:/plugin/org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier">
      <eAnnotations source="org.unicase.ui.meeditor">
        <details key="priority" value="30.0"/>
        <details key="position" value="left"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestStepInput" eSuperTypes="platform:/plugin/org.unicase.model/model/model.ecore#//UnicaseModelElement platform:/plugin/org.unicase.metamodel/model/metamodel.ecore#//NonDomainElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testStep" eType="#//TestStep"
        eOpposite="#//TestStep/input" eKeys="platform:/plugin/org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//TestProtocolToStringMap" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestStepOutput" eSuperTypes="platform:/plugin/org.unicase.model/model/model.ecore#//UnicaseModelElement platform:/plugin/org.unicase.metamodel/model/metamodel.ecore#//NonDomainElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testStep" eType="#//TestStep"
        eOpposite="#//TestStep/output" eKeys="platform:/plugin/org.unicase.metamodel/model/metamodel.ecore#//IdentifiableElement/identifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//TestProtocolToStringMap" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestProtocolToStringMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//TestProtocol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
