// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package microsoftkinectwrapper;

@net.sf.jni4net.attributes.ClrInterface
public interface ISpeechRecognition {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("([LSystem/String;)V")
    void setup(java.lang.String[] args);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    void startRecog();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    java.lang.String getSpeech();
    //</generated-interface>
}
