// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package microsoftkinectwrapper;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class ISpeechRecognition_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return microsoftkinectwrapper.ISpeechRecognition_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        microsoftkinectwrapper.ISpeechRecognition_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __ISpeechRecognition extends system.Object implements microsoftkinectwrapper.ISpeechRecognition {
    
    protected __ISpeechRecognition(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("([LSystem/String;)V")
    public native void setup(java.lang.String[] args);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void startRecog();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getSpeech();
}
//</generated-proxy>
