/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.rationale.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.rationale.Criterion;
import org.unicase.model.rationale.Proposal;
import org.unicase.model.rationale.Solution;
import org.unicase.model.task.ActivityType;

/*
 * A sample validator interface for {@link org.unicase.model.rationale.Issue}. This doesn't really do anything, and it's
 * not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate
 * how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IssueValidator {
	boolean validate();

	boolean validateProposals(EList<Proposal> value);

	boolean validateSolution(Solution value);

	boolean validateCriteria(EList<Criterion> value);

	boolean validateActivity(ActivityType value);
}
