/**
 * <copyright> </copyright> $Id$
 */
package org.unicase.model.rationale.validation;

import org.eclipse.emf.common.util.EList;
import org.unicase.model.rationale.Issue;
import org.unicase.model.rationale.Proposal;

/*
 * A sample validator interface for {@link org.unicase.model.rationale.Solution}. This doesn't really do anything, and
 * it's not a real EMF artifact. It was generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SolutionValidator {
	boolean validate();

	boolean validateUnderlyingProposals(EList<Proposal> value);

	boolean validateIssue(Issue value);
}
